import type { InrPricingAddon, InrPricingComparisonRow, InrPricingPlan } from "@/types/inr-pricing";

/** AI integration service packages — all amounts stored in INR (source of truth). */
export const aiPricingPlans: InrPricingPlan[] = [
  {
    id: "starter-ai",
    name: "Starter AI Package",
    price: { type: "range", minInr: 39999, maxInr: 99999 },
    suitableFor: "Startups, Internal Business Tools, AI Assistants, Small Automation Projects",
    features: [
      "AI Readiness Consultation",
      "LLM Integration",
      "OpenAI / Gemini / Claude Integration",
      "AI Chatbot Development",
      "Prompt Engineering",
      "Basic RAG Implementation",
      "PDF & Document Chat",
      "Knowledge Base Integration",
      "Basic API Integration",
      "Secure Authentication",
      "Testing & Deployment",
      "Documentation",
      "Source Code Delivery",
      "1 Revision Round",
      "Delivery: 2–4 Weeks",
    ],
  },
  {
    id: "business-ai",
    name: "Business AI Package",
    price: { type: "range", minInr: 149999, maxInr: 399999 },
    suitableFor: "Growing Businesses, SaaS Products, Enterprise Automation, Customer Support Platforms",
    popular: true,
    features: [
      "Everything in Starter Package",
      "Advanced RAG Architecture",
      "AI Copilot Development",
      "Enterprise Knowledge Base",
      "Multi-LLM Support",
      "Vector Database Integration",
      "Embedding Pipeline",
      "OCR & Document Intelligence",
      "AI Workflow Automation",
      "Function Calling",
      "API Integrations",
      "Role-Based Access Control",
      "Analytics Dashboard",
      "Performance Optimization",
      "AI Monitoring",
      "Responsible AI Configuration",
      "Security Hardening",
      "Documentation",
      "3 Revision Rounds",
      "Delivery: 1–3 Months",
    ],
  },
  {
    id: "enterprise-ai",
    name: "Enterprise AI Package",
    price: { type: "from", minInr: 599999 },
    suitableFor:
      "Large Enterprises, Healthcare, Finance, Manufacturing, SaaS Platforms, Government, Enterprise AI Transformation",
    features: [
      "Enterprise AI Architecture",
      "Custom AI Copilot Platform",
      "Enterprise RAG Infrastructure",
      "Multi-Agent AI Systems",
      "AI Workflow Orchestration",
      "Multi-LLM Routing",
      "Fine-Tuning Strategy",
      "AI Gateway Implementation",
      "Enterprise Vector Database",
      "Secure Data Pipeline",
      "Document Intelligence Platform",
      "AI Search Engine",
      "AI Analytics & Monitoring",
      "Responsible AI Framework",
      "Human-in-the-Loop Validation",
      "Guardrails & Prompt Security",
      "Compliance & Governance",
      "Performance Optimization",
      "Enterprise Deployment",
      "Priority Support",
      "Unlimited Revisions*",
      "Delivery Based On Scope",
    ],
  },
];

export const aiPricingAddons: InrPricingAddon[] = [
  { id: "openai", name: "OpenAI Integration", price: { type: "single_plus", minInr: 20000 } },
  { id: "claude", name: "Claude Integration", price: { type: "single_plus", minInr: 20000 } },
  { id: "gemini", name: "Gemini Integration", price: { type: "single_plus", minInr: 20000 } },
  { id: "grok", name: "Grok Integration", price: { type: "single_plus", minInr: 20000 } },
  { id: "deepseek", name: "DeepSeek Integration", price: { type: "single_plus", minInr: 20000 } },
  { id: "llama", name: "Llama Deployment", price: { type: "single_plus", minInr: 35000 } },
  { id: "rag", name: "RAG Implementation", price: { type: "single_plus", minInr: 50000 } },
  { id: "vector-db", name: "Vector Database Setup", price: { type: "single_plus", minInr: 35000 } },
  { id: "chatbot", name: "AI Chatbot Development", price: { type: "single_plus", minInr: 40000 } },
  { id: "voice-assistant", name: "AI Voice Assistant", price: { type: "single_plus", minInr: 75000 } },
  { id: "document-intelligence", name: "Document Intelligence", price: { type: "single_plus", minInr: 50000 } },
  { id: "ocr-pipeline", name: "OCR Pipeline Development", price: { type: "single_plus", minInr: 35000 } },
  { id: "workflow-automation", name: "AI Workflow Automation", price: { type: "single_plus", minInr: 45000 } },
  { id: "ai-agent", name: "AI Agent Development", price: { type: "single_plus", minInr: 75000 } },
  { id: "enterprise-kb", name: "Enterprise Knowledge Base", price: { type: "single_plus", minInr: 60000 } },
  { id: "prompt-engineering", name: "Prompt Engineering", price: { type: "single_plus", minInr: 15000 } },
  { id: "security-audit", name: "AI Security Audit", price: { type: "single_plus", minInr: 40000 } },
  { id: "monthly-maintenance", name: "Monthly AI Maintenance", price: { type: "per_month", minInr: 30000 } },
  { id: "dedicated-engineer", name: "Dedicated AI Engineer", price: { type: "custom_quote" } },
];

export const aiPricingComparison: InrPricingComparisonRow[] = [
  { name: "LLM Integration", starter: true, business: true, enterprise: true },
  { name: "AI Chatbot", starter: true, business: true, enterprise: true },
  { name: "RAG Implementation", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Document Intelligence", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Vector Database", starter: "✗", business: true, enterprise: true },
  { name: "Multi-LLM Support", starter: "✗", business: true, enterprise: true },
  { name: "AI Agents", starter: "✗", business: "Basic", enterprise: "Advanced" },
  { name: "Workflow Automation", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Responsible AI", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Security & Guardrails", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Support", starter: "15 Days", business: "30 Days", enterprise: "90 Days" },
  {
    name: "Price",
    starter: { type: "from_plus", minInr: 39999 },
    business: { type: "from_plus", minInr: 149999 },
    enterprise: { type: "from_plus", minInr: 599999 },
  },
];
