import type { InrPricingAddon, InrPricingComparisonRow, InrPricingPlan } from "@/types/inr-pricing";

/** Mobile app development packages — all amounts stored in INR (source of truth). */
export const mobilePricingPlans: InrPricingPlan[] = [
  {
    id: "starter-app",
    name: "Starter App Package",
    price: { type: "range", minInr: 29999, maxInr: 59999 },
    suitableFor: "Startups, Local Businesses, Service Providers, MVP Applications",
    features: [
      "Android App Development",
      "Up to 10 Screens",
      "Responsive UI Design",
      "User Login & Registration",
      "Profile Management",
      "Contact Forms",
      "Push Notifications",
      "Basic API Integration",
      "Firebase Integration",
      "Basic Analytics Setup",
      "App Icon Design",
      "APK Build",
      "Basic Testing",
      "Source Code Delivery",
      "1 Revision Round",
      "Delivery: 2–4 Weeks",
    ],
  },
  {
    id: "business-app",
    name: "Business App Package",
    price: { type: "range", minInr: 79999, maxInr: 199999 },
    suitableFor: "Growing Businesses, E-commerce Apps, Booking Platforms, Business Automation Apps",
    popular: true,
    features: [
      "Android + iOS Development",
      "Up to 25 Screens",
      "Premium UI/UX Design",
      "Advanced User Authentication",
      "Payment Gateway Integration",
      "Push Notifications",
      "Real-Time Features",
      "Advanced API Integrations",
      "Admin Dashboard",
      "Analytics Dashboard",
      "Social Login Integration",
      "Cloud Database Setup",
      "Performance Optimization",
      "App Store Submission Support",
      "Security Optimization",
      "Documentation",
      "3 Revision Rounds",
      "Delivery: 1–3 Months",
    ],
  },
  {
    id: "enterprise-app",
    name: "Enterprise App Package",
    price: { type: "from", minInr: 299999 },
    suitableFor:
      "Large Businesses, SaaS Platforms, Enterprise Mobility Solutions, Marketplaces, On-Demand Platforms",
    features: [
      "Android App",
      "iOS App",
      "Cross-Platform or Native Development",
      "Unlimited Screens",
      "Custom UI/UX Design",
      "Enterprise Architecture",
      "Multi-Role Systems",
      "Advanced API Development",
      "ERP / CRM Integration",
      "AI Integration Ready",
      "Real-Time Communication",
      "Advanced Analytics",
      "Offline Sync Capability",
      "Multi-Language Support",
      "High Security Standards",
      "Performance Optimization",
      "CI/CD Deployment Setup",
      "App Store & Play Store Deployment",
      "Technical Documentation",
      "Priority Support",
      "Unlimited Revisions*",
      "Delivery Based On Scope",
    ],
  },
];

export const mobilePricingAddons: InrPricingAddon[] = [
  {
    id: "additional-platform",
    name: "Additional Platform Support",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "flutter",
    name: "Flutter Development",
    price: { type: "single_plus", minInr: 20000 },
  },
  {
    id: "react-native",
    name: "React Native Development",
    price: { type: "single_plus", minInr: 20000 },
  },
  {
    id: "native-android",
    name: "Native Android Development",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "native-ios",
    name: "Native iOS Development",
    price: { type: "single_plus", minInr: 35000 },
  },
  {
    id: "payment-gateway",
    name: "Payment Gateway Integration",
    price: { type: "single_plus", minInr: 10000 },
  },
  {
    id: "gps-maps",
    name: "GPS & Maps Integration",
    price: { type: "single_plus", minInr: 12000 },
  },
  {
    id: "chat-system",
    name: "Chat System Integration",
    price: { type: "single_plus", minInr: 15000 },
  },
  {
    id: "video-calling",
    name: "Video Calling Integration",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "ai-chatbot",
    name: "AI Chatbot Integration",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "admin-panel",
    name: "Admin Panel Development",
    price: { type: "single_plus", minInr: 20000 },
  },
  {
    id: "app-store-publishing",
    name: "App Store Publishing",
    price: { type: "single_plus", minInr: 7500 },
  },
  {
    id: "play-store-publishing",
    name: "Play Store Publishing",
    price: { type: "single_plus", minInr: 5000 },
  },
  {
    id: "maintenance",
    name: "Maintenance & Support",
    price: { type: "per_month", minInr: 10000 },
  },
];

export const mobilePricingComparison: InrPricingComparisonRow[] = [
  { name: "Android App", starter: true, business: true, enterprise: true },
  { name: "iOS App", starter: false, business: true, enterprise: true },
  { name: "Responsive UI", starter: true, business: true, enterprise: true },
  { name: "API Integration", starter: "Basic", business: "Advanced", enterprise: "Unlimited" },
  { name: "Push Notifications", starter: true, business: true, enterprise: true },
  { name: "Admin Dashboard", starter: false, business: true, enterprise: true },
  { name: "Payment Gateway", starter: "Optional", business: true, enterprise: true },
  { name: "Multi-Language", starter: false, business: "Optional", enterprise: true },
  { name: "Analytics", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Security", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Support", starter: "15 Days", business: "30 Days", enterprise: "90 Days" },
  {
    name: "Price",
    starter: { type: "from_plus", minInr: 29999 },
    business: { type: "from_plus", minInr: 79999 },
    enterprise: { type: "from_plus", minInr: 299999 },
  },
];
