import type { InrPricingAddon, InrPricingComparisonRow, InrPricingPlan } from "@/types/inr-pricing";

/** Custom software development packages — all amounts stored in INR (source of truth). */
export const softwarePricingPlans: InrPricingPlan[] = [
  {
    id: "starter-software",
    name: "Starter Software Package",
    price: { type: "range", minInr: 24999, maxInr: 49999 },
    suitableFor: "Startups, Small Businesses, Internal Tools, Basic Automation Systems",
    features: [
      "Requirement Analysis",
      "Custom Software Development",
      "Responsive Web Application",
      "User Authentication",
      "Admin Panel",
      "Dashboard",
      "Database Integration",
      "Basic Reporting",
      "Role Management",
      "Basic Security Setup",
      "API Integration (Up to 2 APIs)",
      "Testing & Deployment",
      "Source Code Delivery",
      "1 Revision Round",
      "Delivery: 2–4 Weeks",
    ],
  },
  {
    id: "business-software",
    name: "Business Software Package",
    price: { type: "range", minInr: 74999, maxInr: 199999 },
    suitableFor: "Growing Businesses, Manufacturing Companies, ERP Modules, CRM Systems",
    popular: true,
    features: [
      "Everything in Starter Package",
      "Advanced Admin Panel",
      "Multi User Roles",
      "Advanced Reporting",
      "Custom Workflow Automation",
      "Inventory Management",
      "CRM Functionality",
      "Lead Management",
      "Employee Management",
      "Advanced Database Architecture",
      "API Integrations (Up to 10 APIs)",
      "Third-Party Integrations",
      "Cloud Deployment",
      "Security Hardening",
      "Performance Optimization",
      "Documentation",
      "3 Revision Rounds",
      "Delivery: 1–3 Months",
    ],
  },
  {
    id: "enterprise-software",
    name: "Enterprise Software Package",
    price: { type: "from", minInr: 299999 },
    suitableFor:
      "Large Enterprises, SaaS Platforms, ERP Systems, Portals, Marketplace Platforms, Enterprise Automation",
    features: [
      "Unlimited Modules",
      "Fully Custom Architecture",
      "Enterprise Dashboard",
      "Advanced User Permissions",
      "Multi-Tenant Support",
      "Microservice Architecture",
      "High Scalability Infrastructure",
      "Enterprise Security",
      "API Development",
      "Unlimited Third-Party Integrations",
      "Custom Automation Systems",
      "Cloud Infrastructure Setup",
      "AI Integration Ready",
      "Analytics & Reporting",
      "Audit Logs",
      "CI/CD Deployment",
      "Performance Optimization",
      "Technical Documentation",
      "Priority Support",
      "Unlimited Revisions*",
      "Delivery Based On Scope",
    ],
  },
];

export const softwarePricingAddons: InrPricingAddon[] = [
  {
    id: "mobile-app",
    name: "Mobile App Development",
    price: { type: "single_plus", minInr: 49999 },
  },
  {
    id: "android",
    name: "Android Application",
    price: { type: "single_plus", minInr: 29999 },
  },
  {
    id: "ios",
    name: "iOS Application",
    price: { type: "single_plus", minInr: 39999 },
  },
  {
    id: "desktop",
    name: "Desktop Application",
    price: { type: "single_plus", minInr: 39999 },
  },
  {
    id: "api-dev",
    name: "API Development",
    price: { type: "single_plus", minInr: 15000 },
  },
  {
    id: "payment-gateway",
    name: "Payment Gateway Integration",
    price: { type: "single_plus", minInr: 10000 },
  },
  {
    id: "sms-gateway",
    name: "SMS Gateway Integration",
    price: { type: "single_plus", minInr: 7500 },
  },
  {
    id: "whatsapp-api",
    name: "WhatsApp API Integration",
    price: { type: "single_plus", minInr: 15000 },
  },
  {
    id: "ai-chatbot",
    name: "AI Chatbot Integration",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "cloud-hosting",
    name: "Cloud Hosting Setup",
    price: { type: "single_plus", minInr: 15000 },
  },
  {
    id: "maintenance",
    name: "Maintenance Package",
    price: { type: "per_month", minInr: 10000 },
  },
  {
    id: "annual-support",
    name: "Annual Support Contract",
    price: { type: "custom_quote" },
  },
];

export const softwarePricingComparison: InrPricingComparisonRow[] = [
  { name: "Custom Development", starter: true, business: true, enterprise: true },
  { name: "Admin Panel", starter: true, business: true, enterprise: true },
  { name: "Database Integration", starter: true, business: true, enterprise: true },
  { name: "Authentication", starter: true, business: true, enterprise: true },
  { name: "API Integrations", starter: "2 APIs", business: "10 APIs", enterprise: "Unlimited" },
  { name: "Automation Workflows", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Cloud Deployment", starter: true, business: true, enterprise: true },
  { name: "Security Setup", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Scalability", starter: "Basic", business: "Medium", enterprise: "High" },
  { name: "Documentation", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Support", starter: "15 Days", business: "30 Days", enterprise: "90 Days" },
  {
    name: "Price",
    starter: { type: "from_plus", minInr: 24999 },
    business: { type: "from_plus", minInr: 74999 },
    enterprise: { type: "from_plus", minInr: 299999 },
  },
];
