import type { InrPricingAddon, InrPricingComparisonRow, InrPricingPlan } from "@/types/inr-pricing";

/** Staff augmentation service packages — all amounts stored in INR (source of truth). */
export const staffingPricingPlans: InrPricingPlan[] = [
  {
    id: "starter-staff",
    name: "Starter Staff Package",
    price: { type: "range_per_month", minInr: 79999, maxInr: 149999 },
    suitableFor: "Startups, MVP Development, Small Businesses, Short-Term Projects",
    features: [
      "1 Dedicated Senior Engineer",
      "10-Day Onboarding",
      "Full-Time Availability",
      "Agile Collaboration",
      "Daily Progress Updates",
      "Weekly Sprint Meetings",
      "Git Workflow Integration",
      "Documentation",
      "Time Tracking",
      "Direct Communication",
      "Knowledge Transfer",
      "1 Replacement Guarantee",
      "Delivery Support",
    ],
  },
  {
    id: "business-staff",
    name: "Business Staff Package",
    price: { type: "range_per_month", minInr: 249999, maxInr: 699999 },
    suitableFor: "Growing Companies, SaaS Platforms, Product Teams, Enterprise Projects",
    popular: true,
    features: [
      "Dedicated Engineering Team",
      "Senior Software Engineers",
      "UI/UX Designers",
      "QA Engineers",
      "DevOps Engineer",
      "Project Coordinator",
      "10-Day Onboarding",
      "Agile Scrum Workflow",
      "Sprint Planning",
      "Code Reviews",
      "Architecture Support",
      "CI/CD Collaboration",
      "Weekly Reports",
      "Team Scaling",
      "2 Replacement Guarantees",
      "Dedicated Account Manager",
    ],
  },
  {
    id: "enterprise-staff",
    name: "Enterprise Staff Package",
    price: { type: "from_per_month", minInr: 999999 },
    suitableFor:
      "Large Enterprises, Fortune Companies, Long-Term Engineering Partnerships, Digital Transformation Programs",
    features: [
      "Fully Dedicated Engineering Team",
      "Senior Software Architects",
      "AI Engineers",
      "Cloud Architects",
      "DevOps Specialists",
      "UI/UX Team",
      "QA Automation Engineers",
      "Product Managers",
      "Scrum Master",
      "Technical Lead",
      "Enterprise Governance",
      "Architecture Reviews",
      "Security Best Practices",
      "Performance Optimization",
      "Knowledge Management",
      "Flexible Team Scaling",
      "Priority Resource Allocation",
      "Dedicated Delivery Manager",
      "Unlimited Team Expansion",
      "Unlimited Replacements*",
      "Enterprise SLA",
    ],
  },
];

export const staffingPricingAddons: InrPricingAddon[] = [
  {
    id: "full-stack",
    name: "Senior Full Stack Developer",
    price: { type: "per_month", minInr: 150000 },
  },
  {
    id: "frontend",
    name: "Frontend Developer",
    price: { type: "per_month", minInr: 120000 },
  },
  {
    id: "backend",
    name: "Backend Developer",
    price: { type: "per_month", minInr: 130000 },
  },
  {
    id: "mobile-dev",
    name: "Mobile App Developer",
    price: { type: "per_month", minInr: 140000 },
  },
  {
    id: "uiux",
    name: "UI/UX Designer",
    price: { type: "per_month", minInr: 110000 },
  },
  {
    id: "devops",
    name: "DevOps Engineer",
    price: { type: "per_month", minInr: 175000 },
  },
  {
    id: "cloud-architect",
    name: "Cloud Architect",
    price: { type: "per_month", minInr: 200000 },
  },
  {
    id: "ai-ml",
    name: "AI/ML Engineer",
    price: { type: "per_month", minInr: 220000 },
  },
  {
    id: "qa-automation",
    name: "QA Automation Engineer",
    price: { type: "per_month", minInr: 130000 },
  },
  {
    id: "project-manager",
    name: "Project Manager",
    price: { type: "per_month", minInr: 180000 },
  },
  {
    id: "tech-architect",
    name: "Technical Architect",
    price: { type: "per_month", minInr: 250000 },
  },
  {
    id: "scrum-master",
    name: "Dedicated Scrum Master",
    price: { type: "per_month", minInr: 160000 },
  },
  {
    id: "production-support",
    name: "24×7 Production Support",
    price: { type: "custom_quote" },
  },
  {
    id: "odc",
    name: "Offshore Development Center (ODC)",
    price: { type: "custom_quote" },
  },
];

export const staffingPricingComparison: InrPricingComparisonRow[] = [
  { name: "Senior Engineers", starter: "1", business: "Team", enterprise: "Unlimited" },
  { name: "10-Day Onboarding", starter: true, business: true, enterprise: true },
  { name: "Flexible Scaling", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Dedicated Resources", starter: true, business: true, enterprise: true },
  { name: "Agile Collaboration", starter: true, business: true, enterprise: true },
  { name: "Project Management", starter: "Basic", business: true, enterprise: true },
  { name: "Architecture Support", starter: "✗", business: true, enterprise: true },
  { name: "Replacement Guarantee", starter: "1", business: "2", enterprise: "Unlimited" },
  { name: "Priority Support", starter: "✗", business: true, enterprise: true },
  { name: "Enterprise SLA", starter: "✗", business: "✗", enterprise: true },
  { name: "Support", starter: "Business Hours", business: "Extended", enterprise: "24×7" },
  {
    name: "Price",
    starter: { type: "from_plus_per_month", minInr: 79999 },
    business: { type: "from_plus_per_month", minInr: 249999 },
    enterprise: { type: "from_plus_per_month", minInr: 999999 },
  },
];
