import type { InrPricingAddon, InrPricingComparisonRow, InrPricingPlan } from "@/types/inr-pricing";

/** Cloud solutions & infrastructure packages — all amounts stored in INR (source of truth). */
export const cloudPricingPlans: InrPricingPlan[] = [
  {
    id: "starter-cloud",
    name: "Starter Cloud Package",
    price: { type: "range", minInr: 24999, maxInr: 74999 },
    suitableFor: "Startups, Small Businesses, First-Time Cloud Adoption, Cloud Assessments",
    features: [
      "Cloud Readiness Assessment",
      "AWS / Azure / GCP Consultation",
      "Basic Landing Zone Setup",
      "Single Environment Deployment",
      "Cloud Architecture Review",
      "IAM & Access Configuration",
      "Basic Security Configuration",
      "Monitoring Setup",
      "Cost Optimization Recommendations",
      "Backup Configuration",
      "Infrastructure Documentation",
      "Knowledge Transfer Session",
      "1 Revision Round",
      "Delivery: 1–3 Weeks",
    ],
  },
  {
    id: "business-cloud",
    name: "Business Cloud Package",
    price: { type: "range", minInr: 99999, maxInr: 249999 },
    suitableFor: "Growing Businesses, SaaS Platforms, Manufacturing Companies, Cloud Migration Projects",
    popular: true,
    features: [
      "Everything in Starter Package",
      "Multi-Environment Setup (Dev, Staging, Production)",
      "Cloud Migration Planning",
      "Infrastructure as Code (Terraform)",
      "CI/CD Pipeline Setup",
      "Load Balancer Configuration",
      "Database Migration Support",
      "Security Hardening",
      "Monitoring & Alerting",
      "Disaster Recovery Planning",
      "Backup & Recovery Strategy",
      "Cloud Cost Optimization",
      "Compliance Best Practices",
      "Architecture Documentation",
      "3 Revision Rounds",
      "Delivery: 3–8 Weeks",
    ],
  },
  {
    id: "enterprise-cloud",
    name: "Enterprise Cloud Package",
    price: { type: "from", minInr: 399999 },
    suitableFor:
      "Enterprises, High-Traffic Platforms, SaaS Companies, FinTech, Healthcare, Enterprise Applications",
    features: [
      "Enterprise Cloud Architecture",
      "AWS / Azure / GCP Landing Zone Implementation",
      "Multi-Region Infrastructure",
      "Infrastructure as Code Automation",
      "Advanced DevOps Pipeline Setup",
      "Kubernetes Architecture",
      "Container Orchestration",
      "High Availability Design",
      "Disaster Recovery Architecture",
      "Advanced Monitoring & Observability",
      "Security & Compliance Framework",
      "Identity & Access Governance",
      "Cost Governance & FinOps",
      "Performance Optimization",
      "Infrastructure Documentation",
      "Dedicated Cloud Architect Support",
      "Priority Support",
      "Unlimited Revisions*",
      "Delivery Based On Scope",
    ],
  },
];

export const cloudPricingAddons: InrPricingAddon[] = [
  {
    id: "aws-setup",
    name: "AWS Infrastructure Setup",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "azure-setup",
    name: "Azure Infrastructure Setup",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "gcp-setup",
    name: "GCP Infrastructure Setup",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "cloud-migration",
    name: "Cloud Migration Services",
    price: { type: "single_plus", minInr: 50000 },
  },
  {
    id: "kubernetes",
    name: "Kubernetes Deployment",
    price: { type: "single_plus", minInr: 40000 },
  },
  {
    id: "docker",
    name: "Docker Containerization",
    price: { type: "single_plus", minInr: 20000 },
  },
  {
    id: "cicd",
    name: "CI/CD Pipeline Setup",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "terraform",
    name: "Infrastructure as Code (Terraform)",
    price: { type: "single_plus", minInr: 30000 },
  },
  {
    id: "security-audit",
    name: "Security Audit & Hardening",
    price: { type: "single_plus", minInr: 35000 },
  },
  {
    id: "disaster-recovery",
    name: "Disaster Recovery Planning",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "finops",
    name: "FinOps Cost Optimization Assessment",
    price: { type: "single_plus", minInr: 20000 },
  },
  {
    id: "monitoring",
    name: "Monitoring & Alerting Setup",
    price: { type: "single_plus", minInr: 15000 },
  },
  {
    id: "managed-support",
    name: "Managed Cloud Support",
    price: { type: "per_month", minInr: 20000 },
  },
  {
    id: "dedicated-engineer",
    name: "Dedicated Cloud Engineer",
    price: { type: "custom_quote" },
  },
];

export const cloudPricingComparison: InrPricingComparisonRow[] = [
  { name: "Cloud Assessment", starter: true, business: true, enterprise: true },
  { name: "Landing Zone Setup", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "AWS Support", starter: true, business: true, enterprise: true },
  { name: "Azure Support", starter: true, business: true, enterprise: true },
  { name: "GCP Support", starter: true, business: true, enterprise: true },
  { name: "Migration Planning", starter: "✗", business: true, enterprise: true },
  { name: "Infrastructure as Code", starter: "✗", business: true, enterprise: true },
  { name: "CI/CD Pipelines", starter: "✗", business: true, enterprise: true },
  { name: "Security Hardening", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Disaster Recovery", starter: "Basic", business: true, enterprise: true },
  { name: "FinOps Optimization", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Support", starter: "15 Days", business: "30 Days", enterprise: "90 Days" },
  {
    name: "Price",
    starter: { type: "from_plus", minInr: 24999 },
    business: { type: "from_plus", minInr: 99999 },
    enterprise: { type: "from_plus", minInr: 399999 },
  },
];
