import type { InrPricingAddon, InrPricingComparisonRow, InrPricingPlan } from "@/types/inr-pricing";

/** DevOps & deployment service packages — all amounts stored in INR (source of truth). */
export const devopsPricingPlans: InrPricingPlan[] = [
  {
    id: "starter-devops",
    name: "Starter DevOps Package",
    price: { type: "range", minInr: 19999, maxInr: 59999 },
    suitableFor: "Startups, MVP Products, Small Development Teams, Basic Deployment Automation",
    features: [
      "DevOps Assessment",
      "CI/CD Pipeline Setup",
      "Git Repository Integration",
      "Automated Build Process",
      "Automated Deployment Workflow",
      "Development & Production Environments",
      "Docker Containerization",
      "Server Deployment Setup",
      "Basic Monitoring Configuration",
      "SSL & Security Configuration",
      "Deployment Documentation",
      "Knowledge Transfer Session",
      "1 Revision Round",
      "Delivery: 1–3 Weeks",
    ],
  },
  {
    id: "business-devops",
    name: "Business DevOps Package",
    price: { type: "range", minInr: 79999, maxInr: 249999 },
    suitableFor: "Growing Businesses, SaaS Platforms, E-commerce Platforms, Multi-Team Development",
    popular: true,
    features: [
      "Everything in Starter Package",
      "Advanced CI/CD Pipelines",
      "Infrastructure as Code (Terraform)",
      "Docker Orchestration",
      "Kubernetes Cluster Setup",
      "Blue-Green Deployment Strategy",
      "Rollback Mechanisms",
      "Monitoring & Alerting",
      "Log Management",
      "Security Hardening",
      "Multi-Environment Management",
      "Load Balancer Configuration",
      "Performance Optimization",
      "Disaster Recovery Planning",
      "Architecture Documentation",
      "3 Revision Rounds",
      "Delivery: 3–8 Weeks",
    ],
  },
  {
    id: "enterprise-devops",
    name: "Enterprise DevOps Package",
    price: { type: "from", minInr: 349999 },
    suitableFor:
      "Large Enterprises, SaaS Platforms, High-Traffic Applications, Enterprise Engineering Teams",
    features: [
      "Enterprise DevOps Architecture",
      "Advanced Kubernetes Infrastructure",
      "Multi-Cluster Management",
      "GitOps Implementation",
      "Infrastructure as Code Automation",
      "Advanced CI/CD Strategy",
      "Multi-Cloud Deployment Support",
      "High Availability Infrastructure",
      "Auto Scaling Configuration",
      "Service Mesh Architecture",
      "Enterprise Monitoring & Observability",
      "Security & Compliance Automation",
      "Disaster Recovery Architecture",
      "Performance Engineering",
      "Release Management Framework",
      "DevSecOps Integration",
      "Dedicated DevOps Architect",
      "Priority Support",
      "Unlimited Revisions*",
      "Delivery Based On Scope",
    ],
  },
];

export const devopsPricingAddons: InrPricingAddon[] = [
  {
    id: "kubernetes",
    name: "Kubernetes Deployment",
    price: { type: "single_plus", minInr: 40000 },
  },
  {
    id: "docker",
    name: "Docker Containerization",
    price: { type: "single_plus", minInr: 20000 },
  },
  {
    id: "cicd",
    name: "CI/CD Pipeline Setup",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "github-actions",
    name: "GitHub Actions Automation",
    price: { type: "single_plus", minInr: 15000 },
  },
  {
    id: "gitlab-cicd",
    name: "GitLab CI/CD Setup",
    price: { type: "single_plus", minInr: 20000 },
  },
  {
    id: "jenkins",
    name: "Jenkins Setup & Automation",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "terraform",
    name: "Terraform Infrastructure",
    price: { type: "single_plus", minInr: 30000 },
  },
  {
    id: "monitoring",
    name: "Monitoring & Alerting Setup",
    price: { type: "single_plus", minInr: 15000 },
  },
  {
    id: "elk",
    name: "ELK Stack Deployment",
    price: { type: "single_plus", minInr: 25000 },
  },
  {
    id: "prometheus-grafana",
    name: "Prometheus & Grafana Setup",
    price: { type: "single_plus", minInr: 20000 },
  },
  {
    id: "devsecops",
    name: "DevSecOps Integration",
    price: { type: "single_plus", minInr: 35000 },
  },
  {
    id: "release-management",
    name: "Production Release Management",
    price: { type: "single_plus", minInr: 20000 },
  },
  {
    id: "managed-devops",
    name: "Managed DevOps Support",
    price: { type: "per_month", minInr: 25000 },
  },
  {
    id: "dedicated-engineer",
    name: "Dedicated DevOps Engineer",
    price: { type: "custom_quote" },
  },
];

export const devopsPricingComparison: InrPricingComparisonRow[] = [
  { name: "CI/CD Pipelines", starter: true, business: true, enterprise: true },
  { name: "Docker Support", starter: true, business: true, enterprise: true },
  { name: "Kubernetes", starter: "✗", business: true, enterprise: true },
  { name: "Infrastructure as Code", starter: "✗", business: true, enterprise: true },
  { name: "Monitoring", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Security Automation", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Release Automation", starter: true, business: true, enterprise: true },
  { name: "High Availability", starter: "✗", business: "Basic", enterprise: "Enterprise" },
  { name: "Auto Scaling", starter: "✗", business: "Optional", enterprise: true },
  { name: "GitOps", starter: "✗", business: "✗", enterprise: true },
  { name: "DevSecOps", starter: "✗", business: "Optional", enterprise: true },
  { name: "Support", starter: "15 Days", business: "30 Days", enterprise: "90 Days" },
  {
    name: "Price",
    starter: { type: "from_plus", minInr: 19999 },
    business: { type: "from_plus", minInr: 79999 },
    enterprise: { type: "from_plus", minInr: 349999 },
  },
];
