import type { InrPricingAddon, InrPricingComparisonRow, InrPricingPlan } from "@/types/inr-pricing";

/** Digital transformation service packages — all amounts stored in INR (source of truth). */
export const digitalTransformationPricingPlans: InrPricingPlan[] = [
  {
    id: "starter-transformation",
    name: "Starter Transformation Package",
    price: { type: "range", minInr: 49999, maxInr: 149999 },
    suitableFor: "Startups, Small Businesses, Traditional Businesses Beginning Digital Adoption",
    features: [
      "Digital Transformation Assessment",
      "Business Process Analysis",
      "Technology Readiness Evaluation",
      "Digital Maturity Assessment",
      "Current System Review",
      "Transformation Roadmap",
      "Basic Process Automation Strategy",
      "Cloud Readiness Assessment",
      "Executive Consultation",
      "Implementation Recommendations",
      "Final Strategy Report",
      "Knowledge Transfer Session",
      "1 Revision Round",
      "Delivery: 2–4 Weeks",
    ],
  },
  {
    id: "business-transformation",
    name: "Business Transformation Package",
    price: { type: "range", minInr: 249999, maxInr: 599999 },
    suitableFor: "Growing Businesses, Manufacturing Companies, Retail, Healthcare, Mid-Sized Enterprises",
    popular: true,
    features: [
      "Everything in Starter Package",
      "Enterprise Digital Roadmap",
      "Process Automation Planning",
      "Legacy System Modernization Strategy",
      "ERP / CRM Transformation Planning",
      "Cloud Adoption Strategy",
      "Data Integration Roadmap",
      "Department Workflow Optimization",
      "KPI & Performance Framework",
      "Digital Governance Strategy",
      "Organizational Change Planning",
      "Employee Adoption Strategy",
      "Executive Workshops",
      "Implementation Documentation",
      "Risk Assessment",
      "3 Revision Rounds",
      "Delivery: 1–3 Months",
    ],
  },
  {
    id: "enterprise-transformation",
    name: "Enterprise Transformation Package",
    price: { type: "from", minInr: 999999 },
    suitableFor:
      "Large Enterprises, Government Organizations, Financial Institutions, Manufacturing Groups, Multi-National Companies",
    features: [
      "Enterprise Digital Transformation Strategy",
      "Business Architecture Review",
      "Enterprise Process Reengineering",
      "Organization-Wide Automation Strategy",
      "Enterprise AI Transformation Planning",
      "Cloud Modernization Strategy",
      "ERP & Enterprise System Modernization",
      "Data Strategy & Governance",
      "Executive Leadership Workshops",
      "Change Management Framework",
      "Digital Operating Model",
      "Innovation Roadmap",
      "Enterprise KPI Dashboard Strategy",
      "Vendor Evaluation & Technology Selection",
      "Governance Framework",
      "Transformation PMO Guidance",
      "Executive Reporting",
      "Priority Consulting Support",
      "Unlimited Revisions*",
      "Delivery Based On Scope",
    ],
  },
];

export const digitalTransformationPricingAddons: InrPricingAddon[] = [
  {
    id: "maturity-assessment",
    name: "Digital Maturity Assessment",
    price: { type: "single_plus", minInr: 40000 },
  },
  {
    id: "process-automation",
    name: "Business Process Automation",
    price: { type: "single_plus", minInr: 75000 },
  },
  {
    id: "workflow-optimization",
    name: "Workflow Optimization",
    price: { type: "single_plus", minInr: 50000 },
  },
  {
    id: "erp-transformation",
    name: "ERP Transformation Strategy",
    price: { type: "single_plus", minInr: 80000 },
  },
  {
    id: "crm-modernization",
    name: "CRM Modernization Strategy",
    price: { type: "single_plus", minInr: 60000 },
  },
  {
    id: "legacy-assessment",
    name: "Legacy System Assessment",
    price: { type: "single_plus", minInr: 45000 },
  },
  {
    id: "cloud-adoption-roadmap",
    name: "Cloud Adoption Roadmap",
    price: { type: "single_plus", minInr: 50000 },
  },
  {
    id: "ai-transformation",
    name: "AI Transformation Strategy",
    price: { type: "single_plus", minInr: 90000 },
  },
  {
    id: "data-governance",
    name: "Data Governance Strategy",
    price: { type: "single_plus", minInr: 60000 },
  },
  {
    id: "change-management",
    name: "Change Management Program",
    price: { type: "single_plus", minInr: 75000 },
  },
  {
    id: "leadership-workshop",
    name: "Executive Leadership Workshop",
    price: { type: "single_plus", minInr: 50000 },
  },
  {
    id: "innovation-workshop",
    name: "Innovation Strategy Workshop",
    price: { type: "single_plus", minInr: 60000 },
  },
  {
    id: "digital-pmo",
    name: "Digital PMO Advisory",
    price: { type: "per_month", minInr: 75000 },
  },
  {
    id: "transformation-office",
    name: "Enterprise Transformation Office",
    price: { type: "custom_quote" },
  },
];

export const digitalTransformationPricingComparison: InrPricingComparisonRow[] = [
  { name: "Transformation Roadmap", starter: true, business: true, enterprise: true },
  { name: "Process Automation", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Business Process Analysis", starter: true, business: true, enterprise: true },
  { name: "Cloud Adoption Strategy", starter: "Basic", business: true, enterprise: true },
  { name: "Legacy Modernization", starter: "✗", business: true, enterprise: true },
  { name: "AI Transformation", starter: "✗", business: "Basic", enterprise: "Enterprise" },
  { name: "Change Management", starter: "Basic", business: "Advanced", enterprise: "Enterprise" },
  { name: "Governance Framework", starter: "✗", business: true, enterprise: true },
  { name: "Executive Workshops", starter: "Basic", business: true, enterprise: true },
  { name: "Support", starter: "15 Days", business: "30 Days", enterprise: "90 Days" },
  {
    name: "Price",
    starter: { type: "from_plus", minInr: 49999 },
    business: { type: "from_plus", minInr: 249999 },
    enterprise: { type: "from_plus", minInr: 999999 },
  },
];
