import type { PricingCategory, PricingTier } from "@/types";

/** @deprecated Legacy global tiers — kept for backward compatibility */
export const pricingTiers: PricingTier[] = [
  {
    id: "starter",
    name: "Starter",
    description: "Perfect for startups and small teams launching their first digital product.",
    monthlyPrice: 4999,
    yearlyPrice: 47990,
    features: [
      "Up to 2 dedicated specialists",
      "40 hours / month",
      "Web or mobile development",
      "Weekly progress reports",
      "Email support",
      "Basic analytics setup",
    ],
    cta: "Get Started",
    href: "/contact",
  },
  {
    id: "growth",
    name: "Growth",
    description: "Ideal for growing businesses scaling products and teams.",
    monthlyPrice: 12999,
    yearlyPrice: 124790,
    popular: true,
    features: [
      "Up to 5 dedicated specialists",
      "120 hours / month",
      "Full-stack development",
      "UI/UX design included",
      "Priority support",
      "DevOps & CI/CD setup",
      "Monthly strategy sessions",
    ],
    cta: "Start Growing",
    href: "/contact",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "Custom solutions for large organizations with complex requirements.",
    monthlyPrice: null,
    yearlyPrice: null,
    features: [
      "Dedicated cross-functional team",
      "Unlimited scope & hours",
      "Solution architecture",
      "24/7 premium support",
      "SLA guarantees",
      "Security & compliance",
      "On-site workshops",
      "Executive reporting",
    ],
    cta: "Contact Sales",
    href: "/contact",
  },
];

/** @deprecated Use category comparisonFeatures */
export const comparisonFeatures = [
  { name: "Dedicated team members", starter: "2", growth: "5", enterprise: "Custom" },
  { name: "Monthly hours", starter: "40", growth: "120", enterprise: "Unlimited" },
  { name: "UI/UX design", starter: false, growth: true, enterprise: true },
  { name: "DevOps & CI/CD", starter: false, growth: true, enterprise: true },
  { name: "Priority support", starter: false, growth: true, enterprise: true },
  { name: "24/7 support", starter: false, growth: false, enterprise: true },
  { name: "SLA guarantee", starter: false, growth: false, enterprise: true },
  { name: "Strategy sessions", starter: false, growth: "Monthly", enterprise: "Weekly" },
  { name: "Security audit", starter: false, growth: false, enterprise: true },
];

/**
 * Category-wise pricing — competitive 2026 rates for India/UAE delivery.
 * Three tiers per service: Essential (entry) · Professional (most popular) · Custom quote.
 * All base amounts in USD; regional conversion applied at display time.
 */
export const pricingCategories: PricingCategory[] = [
  {
    id: "custom-software",
    label: "Custom Software",
    description:
      "Bespoke enterprise applications and legacy modernization—Essential discovery, Professional build programs, or a fully custom enterprise scope.",
    serviceHref: "/services/custom-software",
    plans: [
      {
        id: "custom-essential",
        name: "Essential",
        description:
          "Structured discovery sprint with architecture, backlog, and a fixed-price build estimate.",
        priceFromUsd: 1250,
        priceType: "project",
        duration: "2–3 weeks",
        features: [
          "Stakeholder workshops & requirements",
          "Solution architecture & ADRs",
          "Technical risk register",
          "Prioritized product backlog",
          "Fixed-price build proposal",
          "Security & compliance scoping",
        ],
        cta: "Start Discovery",
        href: "/contact",
      },
      {
        id: "custom-professional",
        name: "Professional",
        description:
          "End-to-end custom application delivery with dedicated squad, QA, and DevOps.",
        priceFromUsd: 7500,
        priceType: "project",
        duration: "10–20 weeks",
        popular: true,
        features: [
          "Dedicated cross-functional squad (3–5)",
          "Agile 2-week sprints with demos",
          "Automated testing & CI/CD pipeline",
          "API design & third-party integrations",
          "Staging + production environments",
          "Documentation & knowledge transfer",
          "60-day post-launch support",
        ],
        cta: "Start Build Program",
        href: "/contact",
      },
      {
        id: "custom-custom",
        name: "Custom Quote",
        description:
          "Large-scale platform builds, multi-workstream programs, or legacy modernization with SLA delivery.",
        priceFromUsd: null,
        priceType: "project",
        duration: "Scoped to your needs",
        features: [
          "Program management & PMO",
          "Multi-workstream delivery",
          "Legacy migration (strangler-fig pattern)",
          "Multi-tenant or multi-region architecture",
          "Penetration testing & security audit",
          "Change management & training",
          "24/7 SLA support option",
        ],
        cta: "Get a Quote",
        href: "/contact",
      },
    ],
    comparisonFeatures: [
      { name: "Discovery phase", starter: true, growth: "Included", enterprise: "Extended" },
      { name: "Team size", starter: "2 consultants", growth: "3–5 squad", enterprise: "6–15+ program" },
      { name: "Legacy modernization", starter: "Assessment", growth: "Partial", enterprise: "Full migration" },
      { name: "Automated testing", starter: false, growth: true, enterprise: "Full QA program" },
      { name: "Integrations", starter: "Scoped", growth: "Multiple APIs", enterprise: "ERP/CRM/data warehouse" },
      { name: "Compliance", starter: "Scoping", growth: "Implemented", enterprise: "Audit + pen test" },
      { name: "Documentation", starter: "Architecture", growth: "Full runbooks", enterprise: "Enterprise ADRs" },
      { name: "Support", starter: "30 days", growth: "60 days", enterprise: "SLA retainer" },
    ],
  },
  {
    id: "web-development",
    label: "Web Development",
    description:
      "Marketing sites, SaaS dashboards, and e-commerce—competitive fixed-scope pricing from our Ahmedabad & Dubai delivery teams.",
    serviceHref: "/services/web-development",
    plans: [
      {
        id: "web-essential",
        name: "Essential",
        description:
          "High-converting marketing website or landing hub with CMS, SEO foundation, and Core Web Vitals optimization.",
        priceFromUsd: 875,
        priceType: "project",
        duration: "2–4 weeks",
        features: [
          "Up to 6 responsive pages",
          "Next.js + Tailwind CSS build",
          "Headless CMS setup (Sanity or Contentful)",
          "On-page SEO, sitemap & schema markup",
          "Contact forms + analytics (GA4/GTM)",
          "2 revision rounds & 30-day bug fix window",
        ],
        cta: "Get a Web Quote",
        href: "/contact",
      },
      {
        id: "web-professional",
        name: "Professional",
        description:
          "Custom web application with auth, dashboards, API integrations, and production-grade CI/CD.",
        priceFromUsd: 3250,
        priceType: "project",
        duration: "8–14 weeks",
        popular: true,
        features: [
          "Role-based auth (SSO/OAuth ready)",
          "Admin dashboard + user portal",
          "REST or GraphQL API integrations",
          "Automated testing & CI/CD pipeline",
          "Performance budget & accessibility (WCAG 2.1 AA)",
          "Staging + production environments",
          "Weekly demos & sprint reporting",
        ],
        cta: "Start Your Build",
        href: "/contact",
      },
      {
        id: "web-custom",
        name: "Custom Quote",
        description:
          "Multi-tenant portals, high-traffic commerce, or regulated platforms with SLA-backed delivery.",
        priceFromUsd: null,
        priceType: "project",
        duration: "Scoped to your needs",
        features: [
          "Solution architecture & threat modeling",
          "Multi-region CDN & edge deployment",
          "Compliance mapping (SOC 2, HIPAA, PCI)",
          "Load testing & observability stack",
          "Dedicated squad (4–8 specialists)",
          "24/7 incident response option",
          "Executive steering & quarterly reviews",
        ],
        cta: "Get a Quote",
        href: "/contact",
      },
    ],
    comparisonFeatures: [
      { name: "Pages / modules", starter: "Up to 6", growth: "Custom app", enterprise: "Unlimited scope" },
      { name: "CMS integration", starter: true, growth: true, enterprise: true },
      { name: "User authentication", starter: false, growth: true, enterprise: true },
      { name: "API integrations", starter: "Basic", growth: "Multiple", enterprise: "Enterprise ERP/CRM" },
      { name: "CI/CD pipeline", starter: false, growth: true, enterprise: true },
      { name: "WCAG accessibility", starter: "Best effort", growth: "AA target", enterprise: "AA + audit" },
      { name: "Dedicated team", starter: "2 specialists", growth: "3–4 specialists", enterprise: "4–8+ squad" },
      { name: "Support after launch", starter: "30 days", growth: "60 days", enterprise: "SLA retainer" },
    ],
  },
  {
    id: "mobile",
    label: "Mobile Apps",
    description:
      "iOS and Android apps via React Native or native stacks—MVP through enterprise field-service products at competitive rates.",
    serviceHref: "/services/mobile",
    plans: [
      {
        id: "mobile-essential",
        name: "Essential",
        description:
          "Cross-platform MVP with core flows, auth, and app store submission support.",
        priceFromUsd: 2500,
        priceType: "project",
        duration: "6–10 weeks",
        features: [
          "React Native (iOS + Android)",
          "Up to 10 core screens",
          "Auth, push notifications & offline cache",
          "REST/GraphQL API integration",
          "Firebase analytics & crash reporting",
          "App Store & Play Store submission",
          "TestFlight / internal beta distribution",
        ],
        cta: "Scope Your MVP",
        href: "/contact",
      },
      {
        id: "mobile-professional",
        name: "Professional",
        description:
          "Feature-complete consumer or B2B app with payments, deep linking, and release automation.",
        priceFromUsd: 6250,
        priceType: "project",
        duration: "12–18 weeks",
        popular: true,
        features: [
          "Cross-platform or dual native build",
          "Up to 28 screens + modals",
          "In-app payments (Stripe/Razorpay)",
          "Deep linking & universal links",
          "Fastlane CI/CD release trains",
          "Performance profiling & optimization",
          "App store ASO assets & listing copy",
        ],
        cta: "Build Full App",
        href: "/contact",
      },
      {
        id: "mobile-custom",
        name: "Custom Quote",
        description:
          "Field-service, MDM-compatible, or regulated apps with offline-first sync and enterprise security.",
        priceFromUsd: null,
        priceType: "project",
        duration: "Scoped to your needs",
        features: [
          "Offline-first sync architecture",
          "MDM / enterprise distribution",
          "Certificate pinning & secure storage",
          "Role-based access & audit logging",
          "Integration with ERP/CRM backends",
          "Dedicated mobile squad + QA automation",
          "SLA-backed post-launch support",
        ],
        cta: "Get a Quote",
        href: "/contact",
      },
    ],
    comparisonFeatures: [
      { name: "Platforms", starter: "Cross-platform", growth: "Cross or dual native", enterprise: "Native + MDM" },
      { name: "Screens", starter: "Up to 10", growth: "Up to 28", enterprise: "Unlimited" },
      { name: "Offline mode", starter: "Basic cache", growth: "Sync patterns", enterprise: "Offline-first" },
      { name: "Payments", starter: false, growth: true, enterprise: true },
      { name: "CI/CD (Fastlane)", starter: false, growth: true, enterprise: true },
      { name: "App store submission", starter: true, growth: true, enterprise: true },
      { name: "Security hardening", starter: "Standard", growth: "Enhanced", enterprise: "Enterprise grade" },
      { name: "Post-launch support", starter: "45 days", growth: "60 days", enterprise: "SLA retainer" },
    ],
  },
  {
    id: "design",
    label: "UI/UX Design",
    description:
      "Research-led product design and design systems—entry audits through full product design sprints at accessible rates.",
    serviceHref: "/services/design",
    plans: [
      {
        id: "design-essential",
        name: "Essential",
        description:
          "Heuristic evaluation, accessibility scan, and prioritized redesign roadmap for an existing product.",
        priceFromUsd: 625,
        priceType: "project",
        duration: "1–2 weeks",
        features: [
          "Heuristic & competitive analysis",
          "WCAG 2.1 accessibility scan",
          "User flow & friction mapping",
          "Prioritized improvement backlog",
          "Wireframe concepts for top 3 screens",
          "Executive summary presentation",
        ],
        cta: "Book UX Audit",
        href: "/contact",
      },
      {
        id: "design-professional",
        name: "Professional",
        description:
          "End-to-end UX from research through high-fidelity UI, prototypes, and developer-ready handoff.",
        priceFromUsd: 2000,
        priceType: "project",
        duration: "4–8 weeks",
        popular: true,
        features: [
          "User interviews & journey mapping (4–6 users)",
          "Information architecture & wireframes",
          "High-fidelity UI for up to 20 screens",
          "Interactive Figma prototype",
          "Design system starter (tokens + components)",
          "Usability test round with findings",
          "Dev handoff specs & redlines",
        ],
        cta: "Start Design Sprint",
        href: "/contact",
      },
      {
        id: "design-custom",
        name: "Custom Quote",
        description:
          "Enterprise design system, multi-product consistency, and embedded design support for active squads.",
        priceFromUsd: null,
        priceType: "project",
        duration: "Scoped to your needs",
        features: [
          "Full design system (Figma + Storybook)",
          "Embedded senior product designer",
          "Sprint-level design support (2-week cadence)",
          "Design QA on every release",
          "Accessibility champion reviews",
          "Multi-brand / white-label variants",
          "Retainer or program pricing available",
        ],
        cta: "Get a Quote",
        href: "/contact",
      },
    ],
    comparisonFeatures: [
      { name: "User research sessions", starter: "Desk research", growth: "4–6 interviews", enterprise: "Ongoing program" },
      { name: "Hi-fi screens", starter: "3 concepts", growth: "Up to 20", enterprise: "Unlimited" },
      { name: "Interactive prototype", starter: false, growth: true, enterprise: true },
      { name: "Design system", starter: false, growth: "Starter kit", enterprise: "Full system" },
      { name: "Usability testing", starter: false, growth: "1 round", enterprise: "Continuous" },
      { name: "Developer handoff", starter: "Basic", growth: "Full specs", enterprise: "Embedded pairing" },
      { name: "Accessibility (WCAG)", starter: "Scan only", growth: "AA patterns", enterprise: "AA + testing" },
      { name: "Revision rounds", starter: "2", growth: "3", enterprise: "Agile iterations" },
    ],
  },
  {
    id: "cloud",
    label: "Cloud Solutions",
    description:
      "AWS, Azure, and GCP architecture, migration, and FinOps—assessment through migration programs at competitive project rates.",
    serviceHref: "/services/cloud",
    plans: [
      {
        id: "cloud-essential",
        name: "Essential",
        description:
          "Current-state review, cost baseline, security gaps, and prioritized migration or optimization roadmap.",
        priceFromUsd: 1250,
        priceType: "project",
        duration: "2–3 weeks",
        features: [
          "Infrastructure & cost baseline audit",
          "Well-Architected review (AWS/Azure/GCP)",
          "Security & compliance gap analysis",
          "Migration or modernization roadmap",
          "FinOps quick wins (typical 15–25% savings)",
          "Executive readout & business case",
        ],
        cta: "Request Assessment",
        href: "/contact",
      },
      {
        id: "cloud-professional",
        name: "Professional",
        description:
          "Phased cloud migration with landing zone, IaC, and cutover planning for 8–30 workloads.",
        priceFromUsd: 4750,
        priceType: "project",
        duration: "6–12 weeks",
        popular: true,
        features: [
          "Multi-account landing zone (Terraform/CDK)",
          "IAM, networking & guardrails setup",
          "Migrate 8–30 workloads (lift-shift or refactor)",
          "Database migration with rollback plan",
          "Monitoring, alerting & backup automation",
          "Runbooks & DR testing (game day)",
          "Team training & knowledge transfer",
        ],
        cta: "Plan Migration",
        href: "/contact",
      },
      {
        id: "cloud-custom",
        name: "Custom Quote",
        description:
          "Managed cloud platform, multi-region estates, FinOps, SRE, and compliance for regulated or high-scale environments.",
        priceFromUsd: null,
        priceType: "project",
        duration: "Scoped to your needs",
        features: [
          "Dedicated cloud architect + SRE",
          "Multi-region DR & chaos testing",
          "Compliance evidence (SOC 2, ISO 27001)",
          "24/7 monitoring & incident response",
          "Continuous FinOps & rightsizing",
          "Cost anomaly detection & budgets",
          "Quarterly architecture reviews",
        ],
        cta: "Get a Quote",
        href: "/contact",
      },
    ],
    comparisonFeatures: [
      { name: "Workloads covered", starter: "Assessment only", growth: "8–30", enterprise: "Full estate" },
      { name: "Landing zone / IaC", starter: false, growth: true, enterprise: true },
      { name: "FinOps optimization", starter: "Recommendations", growth: "Implemented", enterprise: "Continuous" },
      { name: "Multi-cloud support", starter: "Advisory", growth: "Single primary", enterprise: "Multi / hybrid" },
      { name: "Compliance mapping", starter: "Gap analysis", growth: "Controls implemented", enterprise: "Audit-ready" },
      { name: "DR & backup testing", starter: false, growth: "Game day", enterprise: "Quarterly DR drills" },
      { name: "24/7 monitoring", starter: false, growth: "Business hours", enterprise: true },
      { name: "Architect access", starter: "Project-based", growth: "Weekly", enterprise: "Dedicated + on-call" },
    ],
  },
  {
    id: "devops",
    label: "DevOps & Deploy",
    description:
      "CI/CD pipelines, Kubernetes, GitOps, and SRE practices—foundation setups through platform engineering at standard market rates.",
    serviceHref: "/services/devops",
    plans: [
      {
        id: "devops-essential",
        name: "Essential",
        description:
          "Automated build, test, and deploy pipeline with security scanning for a single product or repo.",
        priceFromUsd: 1000,
        priceType: "project",
        duration: "2–3 weeks",
        features: [
          "GitHub Actions / GitLab CI pipeline",
          "Automated unit & integration tests",
          "Container build & registry setup",
          "Staging + production deploy workflows",
          "SAST/dependency vulnerability scanning",
          "Secrets management (Vault / SSM)",
          "Pipeline documentation & team training",
        ],
        cta: "Setup CI/CD",
        href: "/contact",
      },
      {
        id: "devops-professional",
        name: "Professional",
        description:
          "Kubernetes cluster, GitOps, observability stack, and golden-path templates for engineering teams.",
        priceFromUsd: 3000,
        priceType: "project",
        duration: "4–8 weeks",
        popular: true,
        features: [
          "EKS/AKS/GKE cluster provisioning (IaC)",
          "Argo CD or Flux GitOps workflows",
          "Prometheus + Grafana observability",
          "Centralized logging (ELK / Loki)",
          "SLO definitions & alerting rules",
          "Environment promotion (dev → staging → prod)",
          "Developer self-service templates",
        ],
        cta: "Build Platform",
        href: "/contact",
      },
      {
        id: "devops-custom",
        name: "Custom Quote",
        description:
          "Ongoing site reliability, incident management, and platform evolution for mission-critical systems.",
        priceFromUsd: null,
        priceType: "project",
        duration: "Scoped to your needs",
        features: [
          "Dedicated SRE / platform engineer squad",
          "24/7 on-call rotation (optional)",
          "Incident runbooks & postmortems",
          "Monthly reliability & cost reviews",
          "Capacity planning & load testing",
          "Security patch & dependency updates",
          "Executive SLA reporting",
        ],
        cta: "Get a Quote",
        href: "/contact",
      },
    ],
    comparisonFeatures: [
      { name: "CI/CD pipelines", starter: "1 product", growth: "Multi-env GitOps", enterprise: "Org-wide" },
      { name: "Kubernetes", starter: false, growth: true, enterprise: "Multi-cluster" },
      { name: "Observability (metrics/logs/traces)", starter: "Basic", growth: "Full stack", enterprise: "Enterprise APM" },
      { name: "Security scanning in pipeline", starter: true, growth: true, enterprise: true },
      { name: "SLO / error budgets", starter: false, growth: true, enterprise: true },
      { name: "On-call support", starter: false, growth: "Business hours", enterprise: "24/7" },
      { name: "IaC (Terraform)", starter: "Pipeline only", growth: "Cluster + apps", enterprise: "Full platform" },
      { name: "Team training", starter: "2 sessions", growth: "Workshop series", enterprise: "Embedded coaching" },
    ],
  },
  {
    id: "ai",
    label: "AI Integration",
    description:
      "LLM copilots, RAG systems, and intelligent automation—feasibility sprints through production AI features at accessible price points.",
    serviceHref: "/services/ai",
    plans: [
      {
        id: "ai-essential",
        name: "Essential",
        description:
          "Use-case discovery, data readiness check, ROI model, and proof-of-concept for one high-value workflow.",
        priceFromUsd: 1500,
        priceType: "project",
        duration: "2–4 weeks",
        features: [
          "Use-case workshop & ROI modeling",
          "Data inventory & quality assessment",
          "LLM provider evaluation (OpenAI/Azure/Bedrock)",
          "Working PoC for 1 workflow",
          "Evaluation harness & guardrail design",
          "Responsible AI & compliance checklist",
          "Production roadmap & cost projection",
        ],
        cta: "Explore AI PoC",
        href: "/contact",
      },
      {
        id: "ai-professional",
        name: "Professional",
        description:
          "Ship a production RAG copilot, document intelligence, or automation workflow with monitoring.",
        priceFromUsd: 4250,
        priceType: "project",
        duration: "6–12 weeks",
        popular: true,
        features: [
          "RAG pipeline with vector database",
          "Enterprise knowledge base ingestion",
          "Chat UI or API integration",
          "Human-in-the-loop review workflows",
          "Prompt versioning & A/B testing",
          "Cost controls & usage monitoring",
          "PII redaction & audit logging",
        ],
        cta: "Build AI Feature",
        href: "/contact",
      },
      {
        id: "ai-custom",
        name: "Custom Quote",
        description:
          "Multi-use-case AI platform with MLOps, governance, and VPC/private deployment for regulated industries.",
        priceFromUsd: null,
        priceType: "project",
        duration: "Scoped to your needs",
        features: [
          "Private LLM deployment (VPC/on-prem)",
          "Multi-model routing & fallback",
          "Enterprise agent orchestration",
          "Fine-tuning on proprietary data",
          "Model governance & bias testing",
          "Dedicated AI engineering squad",
          "Executive AI strategy workshops",
        ],
        cta: "Get a Quote",
        href: "/contact",
      },
    ],
    comparisonFeatures: [
      { name: "Use cases delivered", starter: "1 PoC", growth: "1 production feature", enterprise: "Multi-use-case platform" },
      { name: "RAG / knowledge base", starter: "Prototype", growth: "Production", enterprise: "Enterprise scale" },
      { name: "Private / VPC deployment", starter: false, growth: "Optional", enterprise: true },
      { name: "Evaluation & monitoring", starter: "Basic", growth: "Full harness", enterprise: "MLOps platform" },
      { name: "Human-in-the-loop", starter: false, growth: true, enterprise: true },
      { name: "Fine-tuning", starter: false, growth: "Optional", enterprise: true },
      { name: "Compliance (PII, audit)", starter: "Checklist", growth: "Implemented", enterprise: "Audit-ready" },
      { name: "Ongoing optimization", starter: false, growth: "30 days", enterprise: "Retainer" },
    ],
  },
  {
    id: "transformation",
    label: "Digital Transformation",
    description:
      "Holistic modernization across process, platform, and people—assessment, program delivery, or fully custom enterprise transformation.",
    serviceHref: "/services/transformation",
    plans: [
      {
        id: "transformation-essential",
        name: "Essential",
        description:
          "Current-state analysis and prioritized initiative portfolio with business case and executive readout.",
        priceFromUsd: 2000,
        priceType: "project",
        duration: "2–4 weeks",
        features: [
          "Stakeholder interviews (10–15)",
          "Capability & maturity mapping",
          "Initiative portfolio with ROI",
          "Business case & executive deck",
          "Risk register & dependencies",
          "Quick-win automation recommendations",
        ],
        cta: "Start Assessment",
        href: "/contact",
      },
      {
        id: "transformation-professional",
        name: "Professional",
        description:
          "Multi-workstream execution with PMO governance, change management, and benefits tracking.",
        priceFromUsd: 10000,
        priceType: "project",
        duration: "4–12 months",
        popular: true,
        features: [
          "PMO cadence & steering support",
          "Vendor coordination & governance",
          "Benefits tracking dashboard",
          "Change management plan",
          "Process automation (RPA/workflows)",
          "Monthly executive reporting",
          "Quarterly roadmap refresh",
        ],
        cta: "Plan Program",
        href: "/contact",
      },
      {
        id: "transformation-custom",
        name: "Custom Quote",
        description:
          "Enterprise-wide transformation across departments, platforms, and operating models with SLA delivery.",
        priceFromUsd: null,
        priceType: "project",
        duration: "Scoped to your needs",
        features: [
          "Multi-department program management",
          "Legacy platform modernization roadmap",
          "Operating model redesign",
          "Continuous improvement retainer option",
          "Innovation backlog & technology radar",
          "Executive steering & board reporting",
          "Dedicated transformation squad",
        ],
        cta: "Get a Quote",
        href: "/contact",
      },
    ],
    comparisonFeatures: [
      { name: "Stakeholder coverage", starter: "10–15 interviews", growth: "Cross-functional", enterprise: "Enterprise-wide" },
      { name: "Initiative portfolio", starter: true, growth: true, enterprise: "Multi-year roadmap" },
      { name: "PMO governance", starter: false, growth: true, enterprise: "Full PMO" },
      { name: "Change management", starter: "Recommendations", growth: "Implemented", enterprise: "Enterprise program" },
      { name: "Process automation", starter: "Quick wins", growth: "Multiple workflows", enterprise: "Org-wide" },
      { name: "Benefits tracking", starter: "Business case", growth: "Live dashboard", enterprise: "Executive KPI suite" },
      { name: "Vendor coordination", starter: false, growth: true, enterprise: "Multi-vendor governance" },
      { name: "Executive reporting", starter: "Readout deck", growth: "Monthly", enterprise: "Board cadence" },
    ],
  },
  {
    id: "consulting",
    label: "IT Consulting",
    description:
      "Technology audits, architecture reviews, and vendor selection from principal architects—focused advisory or ongoing retainer.",
    serviceHref: "/services/consulting",
    plans: [
      {
        id: "consulting-essential",
        name: "Essential",
        description:
          "Targeted review on a specific domain—architecture, security, or vendor selection with actionable recommendations.",
        priceFromUsd: 1000,
        priceType: "project",
        duration: "2–3 weeks",
        features: [
          "Documentation & codebase review",
          "Gap analysis & risk heatmap",
          "Prioritized recommendations",
          "Executive summary deck",
          "2-hour readout workshop",
          "30-day email follow-up support",
        ],
        cta: "Book Advisory",
        href: "/contact",
      },
      {
        id: "consulting-professional",
        name: "Professional",
        description:
          "Monthly access to principal architects for ongoing guidance, vendor evaluation, and roadmap updates.",
        priceFromUsd: 625,
        priceType: "monthly",
        duration: "3+ months",
        popular: true,
        features: [
          "6 hours/month architecture office hours",
          "Vendor evaluation & RFP support",
          "Quarterly technology roadmap",
          "Ad-hoc security & scalability reviews",
          "Board-ready executive summaries",
          "Slack / Teams direct access",
        ],
        cta: "Start Retainer",
        href: "/contact",
      },
      {
        id: "consulting-custom",
        name: "Custom Quote",
        description:
          "Transformation PMO, multi-vendor governance, and program oversight for complex enterprise initiatives.",
        priceFromUsd: null,
        priceType: "project",
        duration: "Scoped to your needs",
        features: [
          "Steering committee support",
          "Cross-vendor risk tracking",
          "Benefits realization reporting",
          "Change management oversight",
          "Weekly status to executives",
          "Dedicated principal consultant squad",
        ],
        cta: "Get a Quote",
        href: "/contact",
      },
    ],
    comparisonFeatures: [
      { name: "Engagement type", starter: "Fixed advisory", growth: "Monthly retainer", enterprise: "Program-based" },
      { name: "Architecture review", starter: "Single domain", growth: "Ongoing", enterprise: "Multi-domain" },
      { name: "Vendor / RFP support", starter: "Lightweight", growth: true, enterprise: "Full RFP cycle" },
      { name: "Executive workshops", starter: "1 readout", growth: "Quarterly", enterprise: "Weekly steering" },
      { name: "Codebase review", starter: true, growth: true, enterprise: true },
      { name: "Security assessment", starter: "Focused", growth: "Ad-hoc", enterprise: "Continuous" },
      { name: "Roadmap updates", starter: false, growth: "Quarterly", enterprise: "Monthly" },
      { name: "PMO oversight", starter: false, growth: false, enterprise: true },
    ],
  },
  {
    id: "staffing",
    label: "Staff Augmentation",
    description:
      "Senior engineers and designers embedded in your team—flexible specialist or squad models with rapid onboarding from India & UAE.",
    serviceHref: "/services/staffing",
    plans: [
      {
        id: "staffing-essential",
        name: "Essential",
        description:
          "Individual senior engineer or designer on your team, your tools and process—ideal for filling a specific skill gap.",
        priceFromUsd: 1000,
        priceType: "monthly",
        duration: "3+ months",
        features: [
          "Senior specialist (4+ yrs exp)",
          "40 hrs/week dedicated",
          "Your repos, tools & ceremonies",
          "Bi-weekly performance check-in",
          "30-day replacement guarantee",
          "Time-to-start avg. 10 days",
        ],
        cta: "Embed Specialist",
        href: "/contact",
      },
      {
        id: "staffing-professional",
        name: "Professional",
        description:
          "Cross-functional pod with tech lead, developers, and QA—delivers on your backlog with velocity reporting.",
        priceFromUsd: 2500,
        priceType: "monthly",
        duration: "6+ months",
        popular: true,
        features: [
          "3–4 specialists (dev + QA)",
          "Tech lead for architecture",
          "Sprint delivery on your backlog",
          "Weekly velocity & burndown reports",
          "Monthly stakeholder review",
          "Ramp up/down with 2-week notice",
        ],
        cta: "Build a Squad",
        href: "/contact",
      },
      {
        id: "staffing-custom",
        name: "Custom Quote",
        description:
          "Full squad plus delivery manager and architecture oversight for large programs or multi-team augmentation.",
        priceFromUsd: null,
        priceType: "monthly",
        duration: "Scoped to your needs",
        features: [
          "Full squad (5–8 members)",
          "Delivery manager + tech lead",
          "Executive reporting cadence",
          "Architecture & code quality oversight",
          "Volume & long-term contract discounts",
          "Dedicated account manager",
        ],
        cta: "Get a Quote",
        href: "/contact",
      },
    ],
    comparisonFeatures: [
      { name: "Team size", starter: "1 specialist", growth: "3–4 pod", enterprise: "5–8+ squad" },
      { name: "Tech lead included", starter: false, growth: true, enterprise: true },
      { name: "Delivery manager", starter: false, growth: false, enterprise: true },
      { name: "Minimum commitment", starter: "3 months", growth: "6 months", enterprise: "Flexible" },
      { name: "Replacement guarantee", starter: "30 days", growth: "30 days", enterprise: "SLA-backed" },
      { name: "Velocity reporting", starter: false, growth: "Weekly", enterprise: "Executive cadence" },
      { name: "Ramp flexibility", starter: "1 specialist", growth: "2-week notice", enterprise: "Program scale" },
      { name: "Skills coverage", starter: "Single role", growth: "Cross-functional", enterprise: "Multi-squad" },
    ],
  },
];

export const defaultPricingCategoryId = "custom-software";

export function getPricingCategoryById(id: string): PricingCategory | undefined {
  return pricingCategories.find((c) => c.id === id);
}
